version: '2'
services:
  kafka:
    image: "landoop/fast-data-dev:2.3.0"
    ports:
      - 9092:9092
      - 3030:3030
      - 29092:29092
      - 2801:2801
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
    hostname: kafka
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_REST_LISTENERS: http://kafka:8082
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx256m
  mongo:
    image: "mongo:5.0"
    ports:
    - 27017:27017
    depends_on:
      - kafka
  iot:
    image: "exercise/iotsrv:0.0.1"
    ports:
    - 8089:8089
    depends_on:
      - kafka
      - mongo
    environment:
      PROFILE: "default"
      SERVER_PORT: "8089"
      DATABASE_PORT:    27017
      MONGO:     "mongo"
      KAFKA:     "kafka"